### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by uditanshu23** [Webwiznitr/hackecho#4]
design a about section somewhat similar to the attached image and add slight animations if possible

<img width="910" alt="hackecho about example" src="https://user-images.githubusercontent.com/68052031/94331504-8fe80880-ffea-11ea-84c2-cd7cc15e353e.png">

**Comment by SHRAVANNARAYAN** [comment]
[aboutus.zip](https://github.com/Webwiznitr/hackecho/files/5288485/aboutus.zip)

**Comment by SHRAVANNARAYAN** [comment]
[aboutus.zip](https://github.com/Webwiznitr/hackecho/files/5288486/aboutus.zip)

**Comment by SHRAVANNARAYAN** [comment]
[echoar.zip](https://github.com/Webwiznitr/hackecho/files/5290301/echoar.zip)
